steps:
  # build redis image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/redis:latest', './redis/.']

  # build image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sql-server:$COMMIT_SHA', '.']

  # push image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sql-server:$COMMIT_SHA']

  # push image redis
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/redis:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'sql-server',
        '--image',
        'gcr.io/$PROJECT_ID/sql-server:$COMMIT_SHA',
        '--region',
        'asia-southeast2',
        '--allow-unauthenticated',
      ]

images:
  - gcr.io/$PROJECT_ID/sql-server
